version: '3'
services:
  db:
    image: 'mariadb:10.2'
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    volumes:
      - './sql:/docker-entrypoint-initdb.d'
      - './.docker_data/db:/var/lib/mysql'
    networks:
      - lognet
    env_file:
      - ./variables/db.env
  api:
    build: ./nodejs
    restart: always
    volumes:
      - './api:/app'
    tty: true
    networks:
      - lognet
    env_file:
      - ./variables/db.env
      - ./variables/auth.env
  nginx:
    image: nginx
    restart: always
    tty: true
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './app/dist:/var/www'
      - './nginx:/etc/nginx/conf.d'
      - './.docker_data/nginx/logs:/var/log/nginx'
    networks:
      - lognet
networks:
  lognet:
    driver: bridge
